CREATE TABLE Organization (
    id INT PRIMARY KEY AUTO_INCREMENT,
    organizationObject TEXT
);
CREATE TABLE Team (
    id INT PRIMARY KEY AUTO_INCREMENT,
    teamObject TEXT
);
CREATE TABLE User (
    id INT PRIMARY KEY AUTO_INCREMENT,
    userObject TEXT
);
CREATE TABLE Task (
    id INT PRIMARY KEY AUTO_INCREMENT,
    taskObject TEXT
);